# Generated by Django 6.0 on 2026-01-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+234', max_length=25)),
                ('about_me', models.TextField(blank=True, default='Say something about yourself')),
                ('license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(default='profile_default.png', upload_to='profile_default.png')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('city', models.CharField(default='Lagos', max_length=180)),
                ('is_buyer', models.BooleanField(default=False, help_text='Looking to buy?')),
                ('is_seller', models.BooleanField(default=False, help_text='Looking to sell?')),
                ('is_agent', models.BooleanField(default=False, help_text='Are you an agent?')),
                ('top_agent', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
