# Generated by Django 6.0 on 2026-01-01 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(default='Default description...update me please user')),
                ('country', models.CharField(default='Nigeria', max_length=50)),
                ('city', models.CharField(default='Lagos', max_length=180)),
                ('postal_code', models.CharField(default='100001', max_length=100)),
                ('street_address', models.CharField(default='Ikeja Avenue', max_length=150)),
                ('property_number', models.IntegerField(default=112)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0.15, help_text='15% trade tax', max_digits=10)),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_floors', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('advert_type', models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent'), ('AUCTION', 'Auction')], default='FOR_SALE', max_length=50)),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('OFFICE', 'Office'), ('WAREHOUSE', 'Warehouse'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='HOUSE', max_length=50)),
                ('cover_photo', models.ImageField(default='property_cover.jpg', upload_to='property_cover_photos/')),
                ('published_status', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='property_sample.jpg', upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
        migrations.CreateModel(
            name='PropertySearch',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='e.g. 3 Bedroom in Lekki', max_length=100)),
                ('criteria', models.JSONField(help_text="JSON of search params, e.g. {'city': 'Lagos', 'price_max': 1000000}")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
