# Generated by Django 6.0 on 2026-01-01 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='The actual price it was sold/rented for', max_digits=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Agent commission %', max_digits=5)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('date_closed', models.DateField(auto_now_add=True)),
                ('deal_description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals_brokered', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals_closed', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
